### ISSUE TITLE
Incorrect 307 Temporary Redirect -> 400 Bad Request after deployment

### ISSUE THREAD

**Issue by bitnom** [jlowin/fastmcp#435]
### Description

Example repo for issue: https://github.com/bitnom/fastmcp-flyio

All my local testing runs without errors. After deployment via a docker image, I see in the fly logs (Upon running a test client):

```
2025-05-13T18:28:05Z app[d891165bed3418] atl [info][05/13/25 18:28:05] INFO     Starting server "My MCP server.py:207
2025-05-13T18:28:05Z app[d891165bed3418] atl [info]                             Metadata Server"...
2025-05-13T18:28:05Z app[d891165bed3418] atl [info]INFO:     Started server process [628]
2025-05-13T18:28:05Z app[d891165bed3418] atl [info]INFO:     Waiting for application startup.
2025-05-13T18:28:05Z app[d891165bed3418] atl [info]INFO:     Application startup complete.
2025-05-13T18:28:05Z app[d891165bed3418] atl [info]INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
2025-05-13T18:28:26Z app[d891165bed3418] atl [info]INFO:     172.16.4.26:36830 - "POST /mcp HTTP/1.1" 307 Temporary Redirect
2025-05-13T18:28:26Z app[d891165bed3418] atl [info]INFO:     172.16.4.26:36844 - "GET /mcp/ HTTP/1.1" 400 Bad Request
2025-05-13T18:28:26Z app[d891165bed3418] atl [info]INFO:     172.16.4.26:36830 - "POST /mcp HTTP/1.1" 307 Temporary Redirect
2025-05-13T18:28:26Z app[d891165bed3418] atl [info]INFO:     172.16.4.26:36844 - "GET /mcp/ HTTP/1.1" 400 Bad Request
2025-05-13T18:29:49Z app[d891165bed3418] atl [info]INFO:     172.16.4.26:49232 - "POST /mcp HTTP/1.1" 307 Temporary Redirect
2025-05-13T18:29:49Z app[d891165bed3418] atl [info]INFO:     172.16.4.26:49250 - "GET /mcp/ HTTP/1.1" 400 Bad Request
```

how to fix this redirect to work with production url?

Test client:
```python
import asyncio
from fastmcp import Client
from fastmcp.client.transports import StreamableHttpTransport

mcp_host = "https://mymcp.fly.dev/mcp"
# mcp_host = "http://127.0.0.1:5000/mcp"

async def example():

    async with Client(StreamableHttpTransport(mcp_host)) as client:
        print(await client.ping())

if __name__ == "__main__":
    asyncio.run(example())
```

client log:
```
uv run fastmcp_client.py 
Error in post_writer: Client error '400 Bad Request' for url 'https://mymcp.fly.dev/mcp'
```

server config:
```python
import asyncio
import logging
from fastmcp import FastMCP
from typing import List, Dict, Any, Optional, Union

mcp = FastMCP("YouTube Transcript & Metadata Server", host="0.0.0.0", base_path="/mcp")  # have tried with and withotu base_path

@mcp.tool()
def fetch_video_data_with_concatenated_transcript() -> List[Dict[str, Any]]:
    """
    test tool

    Returns:
        some text
    """
    return "this is a test"

if __name__ == "__main__":
    # Run the MCP server when the script is executed directly
    asyncio.run(mcp.run_streamable_http_async(transport="streamable-http", port=5000, host="0.0.0.0", log_level="debug"))
```

`EXPOSE 5000` is set in the dockerfile.

### Example Code

```Python

```

### Version Information

```Text
FastMCP version:                                                                      2.3.3
MCP version:                                                                          1.8.0
Python version:                                                                      3.12.7
```

**Comment by jlowin** [comment]
That is weird - I'm not sure offhand and will have to try to replicate

**Comment by bitnom** [comment]
> That is weird - I'm not sure offhand and will have to try to replicate

This will greatly alleviate the cumbersome setup.

Dockerfile:
```Dockerfile
# Install uv
FROM python:3.12-slim AS builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Change the working directory to the `app` directory
WORKDIR /app
ENV UV_COMPILE_BYTECODE=1
# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-editable

# Copy the project into the intermediate image
ADD . /app

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-editable

FROM python:3.12-slim

# Copy the environment, but not the source code
COPY --from=builder --chown=app:app /app/.venv /app/.venv

# Expose the port your app runs on
EXPOSE 8000

# Run the application with optimizations
CMD ["/app/.venv/bin/mymcp"]
```

fly.toml:
```toml
# fly.toml app configuration file generated for avdl on 2025-05-12T14:49:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mymcp'
primary_region = 'atl'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
```

pyproject.toml:
```toml
[project]
name = "mymcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.3.3",
    "uvicorn>=0.34.2",
]

[project.scripts]
mymcp = "mymcp:main"

[dependency-groups]
dev = [
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

src/mymcp/__init__.py:
```python
from fastmcp import FastMCP
from typing import List, Dict, Any, Optional, Union
import uvicorn

mcp = FastMCP("mymcp")

@mcp.tool()
def some_tool():
  """
  Do the thing
  """
  return "did the thing"

def main():
    http_app = mcp.http_app(transport="streamable-http", path="/mcp")
    uvicorn.run(http_app, host="0.0.0.0", port=8000)

if __name__ == "__main__":
    main()

```

then just issue `fly launch` and `fly logs`
